### ISSUE TITLE
Core vs Threads vs Oversubscribed vCPUs

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/Operational-Docs#5]
Do we need to reflect this in the flavor name?
(1) Dedicated Cores
(2) Dedicated Hyperthreads
(3) Oversubscribed vCPU (limited to a factor X)

Letters: v = vCPU (oversubscribed), s = dedicated thread (SMT/HT),  d = dedicated core

**Comment by gesslein** [comment]
I believe the concept of a "Dedicated Hyperthread" is misleading. Hyperthreads on the same Core are sharing resources like execution units and caches. The best thing this could mean is a not-intentionally-oversubscribed Hyperthread.

I think the base could be
(1) vCPU (equals one Hyperthread for x64, oversubscribed, shared)
(2) dCPU (equals one Hyperthread for x64 but only available in "full Core" increments, dedicated)

People that are interested in dedicated CPU performance are probably not very interested in only buying like 1 or 3 cores, so only offering 2, 4, 6... dCPUs should be more than granular enough.

For vCPUs the next differentiation is the level of oversubscription, which is already covered by suffixes.
For dCPU the next differentiation could be disabled hyperthreading and higher clockspeeds, which I think should also be suffixes and optional.

**Comment by garloff** [comment]
Hi Lothar,

A hyperthread has certain dedicated ressources (register file, architectural state,...) and certain shared resources (L2 cache, execution units).
Giving dedicated access to a hyperthread and exposing it as a vCPU is not uncommon for clouds. It normally yields b/w 60% and 100% of a dedicated core depending on how busy the other thread is (with a minimal perf of ~50%).

I continue to believe that all four options are valid:
Vo = highly oversubscribed vCPU
V = moderately oversubscribed vCPU
T = dedicated thread
C = dedicated core

If I understand your proposal, you suggest handing out pairs of HTs that belong together?
So a 2T config would be two pinned HTs of the same core? This has security advantages (though insufficient to remediate L1TF completely) and predictability advantages, but in average performance disadvantages (in not fully loaded clouds). 
You seem to assume that HT is always enabled, which for older Intel CPUs should not be done.

We have optional suffices for higher clockspeeds already, so this is covered. 
A suffix for disabled HT would not be needed. A C in our model would mandate disabled HT *or* reserving the sibling HT of a core handed out (so no other VM can get it).

Thx,
-- Kurt 


Am 2. Juni 2021 12:03:33 MESZ schrieb Lothar Gesslein ***@***.***>:
>I believe the concept of a "Dedicated Hyperthread" is misleading.
>Hyperthreads on the same Core are sharing resources like execution
>units and caches. The best thing this could mean is a
>not-intentionally-oversubscribed Hyperthread.
>
>I think the base could be
>(1) vCPU (equals one Hyperthread for x64, oversubscribed, shared)
>(2) dCPU (equals one Hyperthread for x64 but only available in "full
>Core" increments, dedicated)
>
>People that are interested in dedicated CPU performance are probably
>not very interested in only buying like 1 or 3 cores, so only offering
>2, 4, 6... dCPUs should be more than granular enough.
>
>For vCPUs the next differentiation is the level of oversubscription,
>which is already covered by suffixes.
>For dCPU the next differentiation could be disabled hyperthreading and
>higher clockspeeds, which I think should also be suffixes and optional.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/SovereignCloudStack/Operational-Docs/issues/5#issuecomment-852894800

-- 
Kurt Garloff ***@***.***>, Cologne, Germany
(Sent from Mobile with K9.)

**Comment by garloff** [comment]
I consider this resolved -- please reopen if you disagree.
